/**
 * generate-laravel codegen smoke test — locks the schema → Laravel contract.
 *
 * Runs scripts/generate-laravel.mjs against a temp schema module and asserts:
 *   - config/vapor-chamber.php registers every action (camelCase-normalized)
 *   - action stubs carry the class name, Validator rules per field, result keys
 *   - existing stubs are preserved without --force (user logic survives)
 *   - --force regenerates stubs
 *   - garbage schemas exit(1) with a clear message
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

const script = resolve(process.cwd(), 'scripts', 'generate-laravel.mjs');

const schemaSource = `export default {
  cartAdd: {
    description: 'Add a product to the cart',
    target:  { id: 'number', name: 'string' },
    payload: { qty: 'number', gift: 'boolean', meta: 'any' },
    result:  { count: 'number', total: 'number' },
  },
  order_create: {
    description: 'Create an order from the cart',
    payload: { items: 'array', options: 'object' },
    result:  { orderId: 'string' },
  },
  ping: {
    description: 'Health check with no fields',
  },
  cartCheckout: {
    description: 'Charge the cart and place the order',
    authorize: 'checkout',
    target: { cartId: 'number' },
  },
};
`;

type RunResult = { status: number; stdout: string; stderr: string };

function run(args: string[]): RunResult {
  try {
    const stdout = execFileSync(process.execPath, [script, ...args], { encoding: 'utf8' });
    return { status: 0, stdout, stderr: '' };
  } catch (e: any) {
    return { status: e.status ?? 1, stdout: e.stdout ?? '', stderr: e.stderr ?? '' };
  }
}

describe('generate-laravel — schema → Laravel backend codegen', () => {
  let dir: string;
  let schemaFile: string;
  let out: string;
  const configPath = () => join(out, 'config', 'vapor-chamber.php');
  const actionPath = (name: string) => join(out, 'app', 'Actions', `${name}.php`);

  beforeAll(() => {
    dir = mkdtempSync(join(tmpdir(), 'vc-laravel-gen-'));
    schemaFile = join(dir, 'commands.mjs');
    out = join(dir, 'laravel-out');
    writeFileSync(schemaFile, schemaSource);
    const first = run([schemaFile, '--out', out]);
    expect(first.status, first.stderr).toBe(0);
  });

  afterAll(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('generates the config registry with every action in schema order, keys camelCase-normalized', () => {
    const config = readFileSync(configPath(), 'utf8');
    expect(config).toContain("'handlers' => [");
    expect(config).toContain("'cartAdd'");
    expect(config).toContain('\\App\\Actions\\CartAdd::class');
    // order_create is normalized to camelCase to match the bus
    expect(config).toContain("'orderCreate'");
    expect(config).toContain('\\App\\Actions\\OrderCreate::class');
    expect(config).not.toContain('order_create');
    expect(config).toContain("'ping'");
    expect(config).toContain('\\App\\Actions\\Ping::class');
    expect(config.indexOf("'cartAdd'")).toBeLessThan(config.indexOf("'orderCreate'"));
    expect(config.indexOf("'orderCreate'")).toBeLessThan(config.indexOf("'ping'"));
  });

  it('generates action stubs with class name, docblock, and the invokable signature', () => {
    const stub = readFileSync(actionPath('CartAdd'), 'utf8');
    expect(stub).toContain('namespace App\\Actions;');
    expect(stub).toContain('class CartAdd');
    expect(stub).toContain('Add a product to the cart');
    expect(stub).toContain('@generated by scripts/generate-laravel.mjs');
    expect(stub).toContain(
      'public function __invoke(mixed $target, mixed $payload, ?\\Illuminate\\Contracts\\Auth\\Authenticatable $user): mixed',
    );
  });

  it('derives Validator rules from target/payload field maps', () => {
    const cartAdd = readFileSync(actionPath('CartAdd'), 'utf8');
    expect(cartAdd).toContain('Validator::make(');
    expect(cartAdd).toContain("'target.id' => 'required|numeric',");
    expect(cartAdd).toContain("'target.name' => 'required|string',");
    expect(cartAdd).toContain("'payload.qty' => 'required|numeric',");
    expect(cartAdd).toContain("'payload.gift' => 'required|boolean',");
    // 'any' fields get no rule
    expect(cartAdd).not.toContain("'payload.meta'");
    expect(cartAdd).toContain(')->validate();');

    const orderCreate = readFileSync(actionPath('OrderCreate'), 'utf8');
    expect(orderCreate).toContain("'payload.items' => 'required|array',");
    expect(orderCreate).toContain("'payload.options' => 'required|array',");
  });

  it('emits a Gate::forUser($user)->authorize(...) call ahead of validation when "authorize" is set', () => {
    const stub = readFileSync(actionPath('CartCheckout'), 'utf8');
    expect(stub).toContain('use Illuminate\\Support\\Facades\\Gate;');
    expect(stub).toContain("Gate::forUser($user)->authorize('checkout', [$target, $payload]);");
    expect(stub).toContain('Requires the "checkout" ability');
    // authorization runs before validation — an unauthorized caller learns nothing
    // about the shape of data it isn't allowed to touch
    expect(stub.indexOf('Gate::forUser')).toBeLessThan(stub.indexOf('Validator::make('));
  });

  it('omits the Gate import and call entirely when "authorize" is not set', () => {
    const ping = readFileSync(actionPath('Ping'), 'utf8');
    expect(ping).not.toContain('Gate::forUser');
    expect(ping).not.toContain('use Illuminate\\Support\\Facades\\Gate;');
  });

  it('skips the Validator block entirely when an action declares no target/payload fields', () => {
    const ping = readFileSync(actionPath('Ping'), 'utf8');
    expect(ping).toContain('class Ping');
    expect(ping).not.toContain('Validator::make');
    expect(ping).not.toContain('use Illuminate\\Support\\Facades\\Validator;');
  });

  it('stubs the return array from the result field map keys', () => {
    const stub = readFileSync(actionPath('CartAdd'), 'utf8');
    expect(stub).toContain('// TODO: implement');
    expect(stub).toContain("'count' => null,");
    expect(stub).toContain("'total' => null,");
  });

  it('never overwrites existing action stubs without --force, but always regenerates config', () => {
    const marker = '// USER LOGIC — must survive regeneration';
    const mutated = readFileSync(actionPath('CartAdd'), 'utf8').replace('// TODO: implement', marker);
    writeFileSync(actionPath('CartAdd'), mutated);
    rmSync(configPath());

    const second = run([schemaFile, '--out', out]);
    expect(second.status, second.stderr).toBe(0);
    expect(second.stdout).toContain('skipped');
    expect(readFileSync(actionPath('CartAdd'), 'utf8')).toContain(marker);
    expect(existsSync(configPath()), 'config is a pure registry — always regenerated').toBe(true);
  });

  it('--force overwrites existing action stubs', () => {
    const forced = run([schemaFile, '--out', out, '--force']);
    expect(forced.status, forced.stderr).toBe(0);
    expect(forced.stdout).toContain('overwritten');
    const stub = readFileSync(actionPath('CartAdd'), 'utf8');
    expect(stub).not.toContain('// USER LOGIC');
    expect(stub).toContain('// TODO: implement');
  });

  it('honors --namespace for both stubs and registry', () => {
    const nsOut = join(dir, 'ns-out');
    const r = run([schemaFile, '--out', nsOut, '--namespace', 'Acme\\Vc\\Actions']);
    expect(r.status, r.stderr).toBe(0);
    expect(readFileSync(join(nsOut, 'app', 'Actions', 'Ping.php'), 'utf8')).toContain('namespace Acme\\Vc\\Actions;');
    expect(readFileSync(join(nsOut, 'config', 'vapor-chamber.php'), 'utf8')).toContain(
      '\\Acme\\Vc\\Actions\\Ping::class',
    );
  });

  it('accepts a .json schema file', () => {
    const jsonFile = join(dir, 'commands.json');
    writeFileSync(jsonFile, JSON.stringify({ cartClear: { description: 'Empty the cart', target: { id: 'number' } } }));
    const jsonOut = join(dir, 'json-out');
    const r = run([jsonFile, '--out', jsonOut]);
    expect(r.status, r.stderr).toBe(0);
    expect(readFileSync(join(jsonOut, 'config', 'vapor-chamber.php'), 'utf8')).toContain("'cartClear'");
    expect(readFileSync(join(jsonOut, 'app', 'Actions', 'CartClear.php'), 'utf8')).toContain(
      "'target.id' => 'required|numeric',",
    );
  });

  it('exits(1) with a clear message on garbage schemas', () => {
    const badField = join(dir, 'bad-field.mjs');
    writeFileSync(badField, "export default { cartAdd: { target: { id: 'integer' } } };\n");
    const r1 = run([badField, '--out', join(dir, 'bad-out')]);
    expect(r1.status).toBe(1);
    expect(r1.stderr).toContain('invalid type "integer"');

    const badAuthorize = join(dir, 'bad-authorize.mjs');
    writeFileSync(badAuthorize, "export default { cartCheckout: { authorize: '' } };\n");
    const r1b = run([badAuthorize, '--out', join(dir, 'bad-out')]);
    expect(r1b.status).toBe(1);
    expect(r1b.stderr).toContain('authorize must be a non-empty ability name string');

    const notObject = join(dir, 'bad-shape.mjs');
    writeFileSync(notObject, 'export default 42;\n');
    const r2 = run([notObject, '--out', join(dir, 'bad-out')]);
    expect(r2.status).toBe(1);
    expect(r2.stderr).toContain('Schema must be a plain object');

    const r3 = run([join(dir, 'does-not-exist.mjs')]);
    expect(r3.status).toBe(1);
    expect(r3.stderr).toContain('not found');
  });
});
