/**
 * measure-size — honest shipped-size table for every published entry.
 *
 * The size that matters is brotli of the CODE — comment-free. ESM subpath exports
 * ship unminified (comments included), but the consumer's bundler strips comments
 * and minifies, so measuring the raw dist file would count comment bytes that never
 * reach production. So we esbuild-bundle each export from source, MINIFY (drops
 * comments), externalize vue, then gzip/brotli that — the real over-the-wire cost.
 * IIFE variants already ship minified, so we read the built .min.js directly.
 *
 * Run: node scripts/measure-size.mjs            human table (default)
 *      node scripts/measure-size.mjs --json      machine-readable
 *      node scripts/measure-size.mjs --md         full generated doc (docs/BUNDLE-SIZES.md)
 *
 * `npm run size:doc` writes --md to docs/BUNDLE-SIZES.md; CI regenerates and
 * `git diff --exit-code`s it, so the published numbers can never drift from reality.
 */
import { readFileSync, statSync, existsSync } from 'node:fs';
import zlib from 'node:zlib';
import { build } from 'esbuild';

const pkg = JSON.parse(readFileSync('./package.json', 'utf8'));
const brot = (buf) => zlib.brotliCompressSync(buf, { params: { [zlib.constants.BROTLI_PARAM_QUALITY]: 11 } }).length;
const gzip = (buf) => zlib.gzipSync(buf, { level: 9 }).length;
const kb = (n) => (n / 1024).toFixed(1);

// ESM subpath exports (package.json "exports" subpath → source entry). Measured
// MINIFIED (comment-free) — the cost after a bundler tree-shakes + minifies them.
const esm = [
  ['.', 'src/index.ts'],
  ['./transports', 'src/transports.ts'],
  ['./directives', 'src/directives.ts'],
  ['./transitions', 'src/transitions.ts'],
  ['./ssr', 'src/ssr.ts'],
  ['./vite', 'src/vite-hmr.ts'],
  ['./fast-lane', 'src/fast-lane.ts'],
  ['./observable', 'src/observable.ts'],
  ['./standard-schema', 'src/plugins-schema.ts'],
  ['./alien-signals', 'src/alien-signals.ts'],
  ['./reactive', 'src/reactive.ts'],
];
const iife = [
  ['vapor-chamber (full)', 'dist/vapor-chamber.iife.min.js'],
  ['vapor-chamber-core', 'dist/vapor-chamber-core.iife.min.js'],
  ['vapor-chamber-elements', 'dist/vapor-chamber-elements.iife.min.js'],
];

async function esmRow(name, entry) {
  const r = await build({
    entryPoints: [entry], bundle: true, minify: true, format: 'esm', target: 'es2022',
    external: ['vue', '@vue/devtools-api'], write: false, logLevel: 'silent', legalComments: 'none',
  });
  const buf = Buffer.from(r.outputFiles[0].contents);
  return { name, min: buf.length, gz: gzip(buf), br: brot(buf) };
}

const esmRows = await Promise.all(esm.filter(([, e]) => existsSync(e)).map(([n, e]) => esmRow(n, e)));
const iifeRows = iife.filter(([, f]) => existsSync(f)).map(([name, f]) => {
  const buf = readFileSync(f);
  return { name, min: statSync(f).size, gz: gzip(buf), br: brot(buf) };
});

function mdTable(label, rs) {
  const out = [`| ${label} | min KB | gzip KB | brotli KB |`, `|---|--:|--:|--:|`];
  for (const r of rs) out.push(`| \`${r.name}\` | ${kb(r.min)} | ${kb(r.gz)} | ${kb(r.br)} |`);
  return out.join('\n');
}

if (process.argv.includes('--json')) {
  console.log(JSON.stringify({ esm: esmRows, iife: iifeRows }, null, 2));
} else if (process.argv.includes('--md')) {
  console.log(`<!-- GENERATED by \`npm run size:doc\` (scripts/measure-size.mjs) — do not edit by hand. -->
# Bundle sizes — vapor-chamber v${pkg.version}

All numbers are **minified, comment-free brotli/gzip** — esbuild \`--minify\` for the ESM
exports (so comments never count), the pre-minified \`.min.js\` for IIFE, then brotli q=11 /
gzip level 9. This is the real over-the-wire cost of the *code*, not the commented source.
Regenerated by \`npm run size:doc\`, verified fresh in CI. Hard ceilings: \`scripts/check-size.mjs\`.

## ESM subpath exports

Each row is the cost of importing **only that export**, bundled self-contained with \`vue\`
external. **Read this carefully:** the shared command-bus core (~3.6 KB brotli on its own) is
included in *every* row, so the rows are **not additive** — importing two exports does not cost
their sum (the core is shared once). \`.\` is the full main barrel measured *import-everything*;
your app's tree-shaking drops whatever you don't use (e.g. importing just \`createCommandBus\`
from it is ~3.6 KB brotli, not ${kb(esmRows[0]?.br ?? 0)} KB).

${mdTable('export', esmRows)}

## IIFE variants (\`<script>\` drop-ins)

${mdTable('variant', iifeRows)}`);
} else {
  const pad = (s, n) => String(s).padEnd(n);
  const padl = (s, n) => String(s).padStart(n);
  const line = (a, b, c, d) => `${pad(a, 26)}${padl(b, 9)}${padl(c, 9)}${padl(d, 10)}`;
  console.log(line('entry (minified)', 'min KB', 'gzip KB', 'brotli KB'));
  console.log('-'.repeat(54));
  for (const r of [...esmRows, ...iifeRows]) console.log(line(r.name, kb(r.min), kb(r.gz), kb(r.br)));
}
